library("here")
library("data.table")
path_input <- here::here("data", "highspeed", "decoding", "sub-*", "data", "sub-*_decoding.csv")
path_output <- here::here("data", "data")
system2("echo", args = c(sprintf("load input data: %s", path_input)))
data <- rbindlist(lapply(Sys.glob(path_input), fread))
data.table::fwrite(setDT(data), paste0(path_output, ".tsv"), row.names = FALSE, sep = "\t")
saveRDS(data, paste0(path_output, ".rds"))
system2("echo", args = c(sprintf("successfully exported %s", path_output)))